# Streamlit Cloud Secrets Configuration
# Copy this file and fill in your values for cloud deployment

# GitHub Personal Access Token (for using GitHub Gist as database)
GITHUB_TOKEN = "your_github_token_here"

# GitHub Gist ID (create a gist with messages.json file)
GIST_ID = "your_gist_id_here" 